<?php

return [
    'default' => env('DEFAULT_ERP', 'default'),
    'enabled' => true,
    'multiple_warehouse' => true,
    'display_contact' => false,
    'logger_enabled' => true,
    'auto_create_cash_customer' => true,
    'auto_create_contact' => true,
    'auto_create_ship_to' => true,
    'use_amplify_shipping' => true,
    'add_ship_will_call_option' => true,
    'labels' => [
        'default' => 'Default',
        'facts-erp' => 'Facts ERP 9.3',
        'ecommerce-erp' => 'Commerce Gateway',
        'facts-erp-77' => 'Facts ERP 7.7',
        'csd-erp' => 'CSD ERP',
    ],
    'configurations' => [
        'default' => [
            'version' => '',
            'adapter' => \Amplify\ErpApi\Services\DefaultErpService::class,
            'customer_id_field' => 'id',
            'url' => '',
            'username' => '',
            'password' => '',
            'enabled' => true,
            'multiple_warehouse' => true,
            'use_single_warehouse_cart' => false,
        ],
        'facts-erp' => [ // MOUNTAIN WEST
            'version' => '9.3',
            'adapter' => \Amplify\ErpApi\Services\FactsErpService::class,
            'customer_id_field' => 'customer_code',
            'url' => 'http://internal.mwd1.com/api',
            'username' => '',
            'password' => '',
            'enabled' => true,
            'multiple_warehouse' => false,
            'use_single_warehouse_cart' => false,
        ],
        'facts-erp-77' => [ // SPI SAFETY
            'version' => '7.7',
            'adapter' => \Amplify\ErpApi\Services\FactsErp77Service::class,
            'customer_id_field' => 'customer_code',
            'url' => 'http://remote.spisafety.com:9088/seq_api',
            'username' => '',
            'password' => '',
            'enabled' => true,
            'multiple_warehouse' => false,
            'use_single_warehouse_cart' => false,
        ],
        'ecommerce-erp' => [
            'adapter' => \Amplify\ErpApi\Services\CommerceGatewayService::class,
            'customer_id_field' => 'customer_code',
            'url' => 'http://gatewaydemo.rbscorp.com/gatewayAdmin/GatewayClient',
            'username' => '',
            'password' => '',
            'enabled' => true,
            'multiple_warehouse' => true,
            'use_single_warehouse_cart' => false,
        ],
        'csd-erp' => [ // Steven Engineering
            'version' => '2024.12.8354871',
            'adapter' => \Amplify\ErpApi\Services\CsdErpService::class,
            'customer_id_field' => 'customer_code',
            'token_url' => '',
            'url' => 'https://mingle-ionapi.inforcloudsuite.com/',
            'company_number' => '1',
            'operator_init' => 'sys',
            'client_id' => '',
            'client_secret' => '',
            'username' => '',
            'password' => '',
            'enabled' => true,
            'access_token' => '',
            'expires_at' => '',
            'multiple_warehouse' => false,
            'use_single_warehouse_cart' => false,
        ],
    ],
];
